sudo: required

services:
  - docker

language: go

go_import_path: kolihub.io/kong-ingress

notifications:
  email: true

go:
  - 1.9

after_success:
  - make docker-build docker-push

script:
  - make test build

